name: GitHub Actions
run-name: ${{ github.ref }} branch build 🚀
on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.2'
      - name: Go build
        run: go build -o hello-api-nix hello-api/main.go
      - name: List files
        run: |
          ls ${{ github.workspace }}
